### ISSUE TITLE
Compatibility with Jmix 1.5

### ISSUE THREAD

**Issue by gorbunkov** [cubacn/jmix-ImageCropper#4]
Please build a version on Jmix 1.5.0 and make a PR to include it in Jmix BOM.

**Comment by GuoRuiLv** [comment]
Hi @gorbunkov,

I've built this add-on on Jmix1.5, please merge the PR: https://github.com/jmix-framework/jmix/pull/1562 .

**Comment by GuoRuiLv** [comment]
Hi @gorbunkov,

I've built this add-on on Jmix1.5, please merge the PR: https://github.com/jmix-framework/jmix/pull/1562 .
